### ISSUE TITLE
Exported Image Encoding (PNG) does not survive restarts (after recent update)

### ISSUE THREAD

**Issue by tannernewell** [JonathanTroyer/Progress-Renderer#26]
I set the Exported Image Encoding to "PNG (Unity)", but the Exported Image Encoding reverts to (default) "JPG (Unity)" after relaunching RimWorld. Deleted my configuration file and reproduced the issue with only Harmony, RimWorld + DLCs, and Progress Renderer active.

Looks like this was caused by a change in the recent (Oct. 12) update, since my images saved as PNGs on Oct. 11 and JPGs on Oct. 12. And to be fair, everything works fine when I manually change the setting to PNG... it just doesn't persist when I relaunch RimWorld.

Here's the configuration file... which leads me to believe that the exported image encoding is not saved anywhere (anymore?)?
```<?xml version="1.0" encoding="utf-8"?>
<SettingsBlock>
	<ModSettings Class="ProgressRenderer.PRModSettings">
		<renderZones>False</renderZones>
		<timeOfDay>12</timeOfDay>
		<pixelsPerCell>8</pixelsPerCell>
		<createSubdirs>True</createSubdirs>
		<migratedOutputImageSettings>True</migratedOutputImageSettings>
		<migratedInterval>True</migratedInterval>
	</ModSettings>
</SettingsBlock>

**Comment by TheVillageGuy** [comment]
Ok that must be a config saving bug, I'll look into it asap. I'm sorry for not noticing it earlier, it must have slipped through all the notification I was getting
