### ISSUE TITLE
Race condition when rendering multiple maps

### ISSUE THREAD

**Issue by XenoTheStrange** [JonathanTroyer/Progress-Renderer#30]
The problem of it switching to a random map is due to several instances of the DoRender function running at the same time, so while one changes the map to render it the other is saving _that_ map as the one to return to instead of the proper one:
![image](https://github.com/JonathanTroyer/Progress-Renderer/assets/48196283/9d00933b-e6ee-4bfe-93a0-2af0a2fa61da)

This image should be a good indicator of what's going on.
I'm not sure what a good fix would be without introducing artificial lag by making the functions wait for each-other.

Since the mod needs to switch to another map in order to render it, multiple renders should not happen simultaneously.

_Originally posted by @XenoTheStrange in https://github.com/JonathanTroyer/Progress-Renderer/issues/29#issuecomment-2033145365_

**Comment by XenoTheStrange** [comment]
I was originally trying to figure out / fix how the game would force-switch your map after rendering but it turns out the problem is bigger than that.

**Comment by XenoTheStrange** [comment]
Maybe set some global "Rendering" variable so each map component will wait for the other one to finish rendering before it goes? Idk.

There is something similar that prevents this sort of scenario if one map tries to render while it's already rendering.

**Comment by JonathanTroyer** [comment]
Fixed by https://github.com/JonathanTroyer/Progress-Renderer/commit/3855bfa8505607f5b9fb6cb2249db3d24897336b
