### ISSUE TITLE
Not all colonists rendered

### ISSUE THREAD

**Issue by JonathanTroyer** [JonathanTroyer/Progress-Renderer#7]
It seems that maps with large numbers of colonists (the original report mentioned >1000) may not render all the colonists.

**Comment by JonathanTroyer** [comment]
Looks like this is actually an issue with Camera+ hiding. We should try to disable Camera+ zoom-level simplification if we detect it.

**Comment by TheVillageGuy** [comment]
The original report was probably mine, as I did a test at the time with 10000. However, looking at the [latest version](https://rimworld.gallery/m/RimWorldPorn/t/210/Rimworld-Benchmark-10000-colonists-about-to-wake-up-vanilla-core) it seems do be fine. So as far as I'm concerned this issue can be closed
